#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
shopt -s lastpipe
# set -o xtrace

# a lighter frontend to grep that
# - uses grep instead of find
# - so is not as flexible as find
# - doesn't mess around with arguments

main () {
    local grep=grep
    local dryrun=0
    local verbose=0
    if which ggrep ; then
        grep=ggrep
    fi
    while (( $# )) && [[ "$1" = "---"?* ]] ; do
        case "$1" in
            ---pcregrep) grep=pcregrep;;
            ---dry-run)  dryrun=1;;
            ---verbose)  verbose=1;;
        esac
        shift
    done
    config
    declare -a cmd=(
        "${grep}" \
            "${exclude_dirs[@]}" "${exclude_files[@]}" \
            --binary-files=without-match --recursive "$@"
    )
    if (( verbose || dryrun )) ; then
        >&2 echo -n '+'
        for i in "${cmd[@]}" ; do
            >&2 echo -n " ${i@Q}"
        done
        >&2 echo
    fi
    if (( dryrun )) ; then
        exit 1
    fi
    exec "${cmd[@]}"
}

config () {
    if [[ -e ~/.config/li/lirc.sh ]] ; then
        . ~/.config/li/lirc.sh
    fi
    local config=".lirc.sh"
    local dir="."
    local lastconfig=""
    local lastdir=""
    local liroot=0
    while true ; do
        if [[ -e "${config}" ]] ; then
            . "${config}"
        fi
        if (( liroot )) ; then
            # specify liroot=1 in .lirc.sh
            break
        fi
        if [[ "${dir}" -ef "../${lastdir}" ]] ; then
            break
        fi
        lastconfig="${config}"
        lastdir="${dir}"
        config="../${config}"
        dir="../${dir}"
    done
}

declare -a exclude_dirs=(
    --exclude-dir='vendor'
    --exclude-dir='node_modules'
    --exclude-dir='.cache'
    --exclude-dir='.cpan'

    # version control
    --exclude-dir='.git'
    --exclude-dir='.svn'

    # others from emacs grep.el
    --exclude-dir='SCCS'
    --exclude-dir='RCS'
    --exclude-dir='CVS'
    --exclude-dir='MCVS'
    --exclude-dir='.src'
    --exclude-dir='.hg'
    --exclude-dir='.bzr'
    --exclude-dir='_MTN'
    --exclude-dir='_darcs'
    --exclude-dir='{arch}'
    --exclude-dir='.sass-cache'

    # BigCommerce
    --exclude-dir='parsed/templates'
    --exclude-dir='parsed/scss'

    # emacs
    --exclude-dir='elpa'

    # etc.
    --exclude-dir='zip-cache'
)

declare -a exclude_files=(
    # backups
    --exclude='*~'
    --exclude='#*#'
    --exclude='.*~'
    --exclude='.#*'
    --exclude='*.bak'
    --exclude='*.tmp'
    --exclude='*.old'
    --exclude='*.orig'
    --exclude='*.bak.*'
    --exclude='*.tmp.*'
    --exclude='*.old.*'
    --exclude='*.orig.*'

    # archives
    --exclude='*.zip'
    --exclude='*.jar'
    --exclude='*.sym'

    # compressed files
    --exclude='*.gz'

    # minified/map files
    --exclude='*.min'
    --exclude='*.min.*'
    --exclude='*.css.map'
    --exclude='*.js.map'
    --exclude='*.min.map'
    --exclude='composer.lock'
    --exclude='*.bundle.js'

    # BigCommerce minified
    --exclude='theme-bundle.main.js'
    --exclude='theme.scss.json'
    --exclude='assets/dist/report.html'
    --exclude='parsed/lang.json'
    --exclude='theme-bundle.chunk.*.js'
    --exclude='theme-bundle.head_async.js'

    # projectile
    --exclude='projectile.cache'

    # emacs
    --exclude='ido.last'

    # images
    --exclude='*.gif'
    --exclude='*.jpg'
    --exclude='*.jpeg'
    --exclude='*.png'
    --exclude='*.webp'

    # fonts
    --exclude='*.ttf'
    --exclude='*.otf'
    --exclude='*.ttc'
    --exclude='*.woff'
    --exclude='*.eot'

    # executables and libraries
    --exclude='*.exe'
    --exclude='*.a'
    --exclude='*.o'
    --exclude='*.so'
    --exclude='*.dll'
    --exclude='*.dylib'

    # Legacy Microsoft Office
    --exclude='*.doc'
    --exclude='*.ppt'
    --exclude='*.xls'

    # Media
    --exclude='*.mov'
    --exclude='*.m4a'
    --exclude='*.qt'
    --exclude='*.wma'
    --exclude='*.mp3'
    --exclude='*.m4r'
    --exclude='*.flv'
    --exclude='*.wmv'
    --exclude='*.swf'

    # Dalvik
    --exclude='*.dex'

    # Java
    --exclude='*.class'

    # Misc.
    --exclude='*.bin'
    --exclude='*.lbin'
    --exclude='*.flat'

    # Others from emacs grep.el.  I--exclude='m assuming these are binary
    # formats.
    --exclude='*.ln'
    --exclude='*.blg'
    --exclude='*.bbl'
    --exclude='*.elc'
    --exclude='*.lof'
    --exclude='*.glo'
    --exclude='*.idx'
    --exclude='*.lot'
    --exclude='*.fmt'
    --exclude='*.tfm'
    --exclude='*.fas'
    --exclude='*.lib'
    --exclude='*.mem'
    --exclude='*.x86f'
    --exclude='*.sparcf'
    --exclude='*.dfsl'
    --exclude='*.pfsl'
    --exclude='*.d64fsl'
    --exclude='*.p64fsl'
    --exclude='*.lx64fsl'
    --exclude='*.lx32fsl'
    --exclude='*.dx64fsl'
    --exclude='*.dx32fsl'
    --exclude='*.fx64fsl'
    --exclude='*.fx32fsl'
    --exclude='*.sx64fsl'
    --exclude='*.sx32fsl'
    --exclude='*.wx64fsl'
    --exclude='*.wx32fsl'
    --exclude='*.fasl'
    --exclude='*.ufsl'
    --exclude='*.fsl'
    --exclude='*.dxl'
    --exclude='*.lo'
    --exclude='*.la'
    --exclude='*.gmo'
    --exclude='*.mo'
    --exclude='*.toc'
    --exclude='*.aux'
    --exclude='*.cp'
    --exclude='*.fn'
    --exclude='*.ky'
    --exclude='*.pg'
    --exclude='*.tp'
    --exclude='*.vr'
    --exclude='*.cps'
    --exclude='*.fns'
    --exclude='*.kys'
    --exclude='*.pgs'
    --exclude='*.tps'
    --exclude='*.vrs'
    --exclude='*.pyc'
    --exclude='*.pyo'
    --exclude='*.ri'

    # anroid lol
    --exclude='*.apk'
    --exclude='*.aab'
    --exclude='*.dex'
    --exclude='*.ap_'

    --exclude='*.doc'
    --exclude='*.docx'
    --exclude='*.xls'
    --exclude='*.xlsx'
    --exclude='*.ppt'
    --exclude='*.pptx'
    --exclude='*.pdf'
    --exclude='*.ps'
    --exclude='*.sfd'      # FontForge fonts
)

# functions for inclusion in ~/.config/li/lirc.sh
#                            ./.lirc.sh
#                            ../.lirc.sh
#                            ../../.lirc.sh
#                            etc.
exclude_file () {
    local pattern
    for pattern ; do
        exclude_files+=(--exclude="${pattern}")
    done
}
no_exclude_file () {
    local pattern
    local member
    local -a tmp=()
    for member in "${exclude_files[@]}" ; do
        for pattern ; do
            if [[ "${member}" = --exclude="${pattern}" ]] ; then
                break 2
            fi
        done
        tmp+=("${member}")
    done
    exclude_files=("${tmp[@]}")
}
exclude_dir () {
    local pattern
    for pattern ; do
        exclude_dirs+=(--exclude-dir="${pattern}")
    done
}
no_exclude_dir () {
    local pattern
    local member
    local -a tmp=()
    for member in "${exclude_dirs[@]}" ; do
        for pattern ; do
            if [[ "${member}" = --exclude-dir="${pattern}" ]] ; then
                break 2
            fi
        done
        tmp+=("${member}")
    done
    exclude_dirs=("${tmp[@]}")
}

main "$@"
